In [1]:
import numpy as np

In [2]:
x=[1,2,3,4,5]

In [3]:
y=[[1,2,3],[4,5,6],[7,8,9]]

In [4]:
np.array(x)

array([1, 2, 3, 4, 5])

In [5]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#creating 1-D zero matrix
np.zeros(3)

array([0., 0., 0.])

In [14]:
#creating 2-D zero matrix (for 2_d create 2 bracket)
#it takes to attribute i and j i.e row and column
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros(((3,3,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
np.zeros(((2,2,5)))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [25]:
np.zeros((2,3)) +5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [27]:
np.zeros((2,3))  - 2

array([[-2., -2., -2.],
       [-2., -2., -2.]])

In [28]:
#ones matix
np.ones(3)

array([1., 1., 1.])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
#Identity matix (in this i=j means square matrix )
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.arange(50) #it is 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
np.arange(22,50)

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [35]:
np.arange(50).reshape(5,10)  #arranging data in 5 rows and 10 column

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
np.linspace(0,100,5)    #linear space means all are equally spaced (between 0-10 we need 5 element which are linearly spaced)

array([  0.,  25.,  50.,  75., 100.])

In [45]:
#to get the maximum or minimum number out of a list
m=[1,2,3,4,5]
m=np.array(m)
m.max()

5

In [47]:
#to get the index of max. number 
m.argmax()

4

In [48]:
#to get the index of min. number 
m.argmin()

0

In [40]:
m.min()

1

In [41]:
# to get  the random value
np.random.rand(5)

array([0.94445961, 0.78890882, 0.99409453, 0.54138355, 0.49152327])

In [42]:
#to get the random negative number use randn
np.random.randn(5)

array([ 0.52830698, -0.93721384,  0.06291678,  0.26047264, -0.74159205])

In [44]:
#to get the random integer number between any range
np.random.randint(1,100)

73