In [1]:
import numpy as np

In [7]:
x= np.arange(0,21)

In [8]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
x[5]

5

In [10]:
x[-1]

20

In [11]:
#slicing the list
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[2:5]

array([2, 3, 4])

In [14]:
x[-11:-2]

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [15]:
#changning the value of list between a range
y=x[5:10]=40

In [16]:
y

40

In [17]:
x

array([ 0,  1,  2,  3,  4, 40, 40, 40, 40, 40, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [18]:
#to copy any list (by doing this original list will no get affected)
y=x.copy()

In [19]:
y

array([ 0,  1,  2,  3,  4, 40, 40, 40, 40, 40, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [20]:
y[5:15]=32

In [21]:
y

array([ 0,  1,  2,  3,  4, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 15, 16,
       17, 18, 19, 20])