In [1]:
import numpy as np


In [6]:
x=np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
#x[i][j] to access any number from the matrix 
x[2][3]

13

In [13]:
#slicing the 2D matirx (provide value 2 times becz we are slicing 2D matrix)
x[0:3 , 2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [14]:
#conditional selection
y=np.arange(0,20)
y>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [15]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
y[y>12]

array([13, 14, 15, 16, 17, 18, 19])

In [19]:
y[y<4]

array([0, 1, 2, 3])

In [20]:
y[y%4==2]

array([ 2,  6, 10, 14, 18])

In [21]:
#remainder in the list after dividing by 4 
y[y%4]

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])