In [1]:
import numpy as np

In [2]:
x=np.arange(10)

In [4]:
y=np.arange(10,20)

In [5]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#adding list and storing it to z
z=x+y

In [8]:
z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
z=x*y
z

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [11]:
#trigonometric operations
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [12]:
np.log(y)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [13]:
np.max(x)

9

In [14]:
x.max()

9

In [16]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
b=np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [19]:
c=a+b
c

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42]])

In [20]:
m=np.arange(12).reshape(3,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
n=np.arange(16,28).reshape(4,3)
n

array([[16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [23]:
#note if order is different operation is not possible
o=m+n

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [24]:
#to find the sum of all the element in the list
p=np.arange(12)
p.sum()

66